apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-wheelers-deployment
  labels:
    app: two-wheelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-wheelers
  template:
    metadata:
      labels:
        app: two-wheelers
    spec:
      containers:
      - name: two-wheelers
        image: 968603941340.dkr.ecr.us-east-1.amazonaws.com/shopping-site-two-wheelers:fa6757f2a76b49fdde983a0cf113df520e1c1944
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: two-wheelers-service
  labels:
    app: two-wheelers
spec:
  type: ClusterIP
  selector:
    app: two-wheelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
